### ISSUE TITLE
Host list not viewable on Ubuntu 11.10

### ISSUE THREAD

**Issue by hellocatfood** [zengargoyle/selfcontrol#2]
When using Self Control on Ubuntu 11.10 the host list isn't viewable. It appears as if the size of that part of the window is dictated by the size of the scrollbar. With Ubuntu 11.10 introducing overlay scrollbars it has resulted in that section becoming very small. See the image below for an illustration of this problem

http://i.imgur.com/vTRYZ.png

**Comment by padraic7a** [comment]
For anyone looking up this issue it also works on Ubuntu 12.04.
